### ISSUE TITLE
Location data in vehicles.json not changing

### ISSUE THREAD

**Issue by aaronmfisher** [minikin/swiftui-mapkit#3]
I have altered the data in vehicles.json but when I compile the app and run it, it doesn't change visually. Is it caching somewhere?

**Comment by minikin** [comment]
@aaronmfisher sorry for the late reply. 

It's only used in debug mode, check `VehiclesView.swift` 
```swift
#if DEBUG
struct VehiclesView_Previews : PreviewProvider {
    static var previews: some View {
        NavigationView {
            VehiclesView(vehicles: sampleVehicleResponse)
        }
    }
}
#endif
```
In compiled app, data is fetched for the [server](https://minikin-json-server.herokuapp.com/vehicles). Please, read [README](https://github.com/minikin/swiftui-mapkit/blob/master/README.md) for more details. 

I close the issue for now. Feel free to reopen.

**Comment by aaronfisher** [comment]
Thank you for the info! I deleted the debug code. I then stood up a server for the json file and swapped the URL in API.swift. It is now stuck on the "Loading..." screen when I try to load my own data on a heroku server using "JSON Server". Any reason for this when swapping the data URL?
